### ISSUE TITLE
Additions request

### ISSUE THREAD

**Issue by 1ForeverHD** [buoyantair/awesome-roblox#1]
Hi there! Thanks for this repo, can't believe I'm just discovering it now!

Can I request some additional widely-used and helpful resources, in addition to my own?

**Frameworks**
- Knit https://github.com/Sleitnick/Knit

**Tools**
- Janitor https://github.com/howmanysmall/Janitor
- Maid https://devforum.roblox.com/t/how-to-use-a-maid-class-on-roblox-to-manage-state/340061
- Signal https://quenty.github.io/api/classes/Signal.html
- RotatedRegion3 https://devforum.roblox.com/t/rotated-region-3-module/334068
- TopbarPlus https://devforum.roblox.com/t/topbarplus-v2/1017485
- ZonePlus https://devforum.roblox.com/t/zoneplus-v2/1017701

**Learning**
- CKStudio+ https://studioplus.io/en

**Comment by elevenpassin** [comment]
@1ForeverHD Hello! Absolutely!! Feel free to send a PR and I'll definitely merge them, these are some amazing resources!
