### ISSUE TITLE
Page not found - 404

### ISSUE THREAD

**Issue by ryanlua** [buoyantair/awesome-roblox#3]
The website which can be found [here](https://buoyantair.co/awesome-roblox/) returns a 404 and doesn't work.

![image](https://github.com/elevenpassin/awesome-roblox/assets/80087248/966413c0-8c5e-46b0-8fd4-9755f40e8746)

**Comment by elevenpassin** [comment]
Website is now published at this URL: https://elevenpassin.github.io/awesome-roblox/

**Comment by ryanlua** [comment]
> Website is now published at this URL: https://elevenpassin.github.io/awesome-roblox/

The repository website should be updated to point to this link than instead of the old one as many aren't going to search through issues for the website.
